//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICE_Import.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DatabaseLocal" +
            ".mdf;Integrated Security=True")]
        public string LocalDatabaseConnectionString {
            get {
                return ((string)(this["LocalDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=h9ggwlagd1.database.windows.net;Initial Catalog=TMLDB_Copy;User ID=da" +
            "taupdate;Password=6dcEpZKSFRNYk^AN;Encrypt=False;TrustServerCertificate=True")]
        public string TMLDB_CopyConnectionString {
            get {
                return ((string)(this["TMLDB_CopyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=h9ggwlagd1.database.windows.net;Initial Catalog=TMLDB;User ID=dataupd" +
            "ate;Password=6dcEpZKSFRNYk^AN;Encrypt=False;TrustServerCertificate=True")]
        public string TMLDBConnectionString {
            get {
                return ((string)(this["TMLDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=h9ggwlagd1.database.windows.net;Initial Catalog=TMLDB;User ID=steve@h" +
            "9ggwlagd1;Password=KYYAtv9P;Encrypt=False;TrustServerCertificate=True")]
        public string TMLDBConnectionString1 {
            get {
                return ((string)(this["TMLDBConnectionString1"]));
            }
        }
    }
}
