<?xml version="1.0" encoding="utf-8"?><Database Name="TMLDB" Class="DataClassesTMLDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=h9ggwlagd1.database.windows.net;Initial Catalog=TMLDB;User ID=dataupdate;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="ICE_Import.Properties.Settings" SettingsPropertyName="TMLDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="cqgdb.tblinstruments" Member="tblinstruments">
    <Type Name="tblinstrument">
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="symbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="exchangesymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="optionexchangesymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="exchangesymbolTT" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="optionexchangesymbolTT" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="idinstrumentgroup" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="idexchange" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="margin" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commissionpercontract" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="modeled" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="listedspread" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="datastart" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="timeshifthours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ticksize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="tickdisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="tickvalue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optionstrikeincrement" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optionstrikedisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optionstrikedisplayTT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optionticksize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optiontickdisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optiontickvalue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="secondaryoptionticksize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="secondaryoptiontickvalue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="secondaryoptiontickdisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="secondaryoptionticksizerule" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="spanticksize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="spantickdisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="spanstrikedisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="spanoptionticksize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="spanoptiontickdisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optionadmstrikedisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="admoptionftpfilestrikedisplay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optionstart" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="spanoptionstart" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="stoptype" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="pricebandinticks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="limittickoffset" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="customdayboundarytime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="usedailycustomdata" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="decisionoffsetminutes" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="optionenabled" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="productionenabled" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="admcode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="admexchangecode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="admfuturepricefactor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="admoptionpricefactor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="spanfuturecode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="spanoptioncode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="optiondatamonthscollected" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="idAssetClass" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="substitutesymbol_eod" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="instrumentsymbol_pre_eod" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="instrumentsymboleod_eod" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="instrumentid_eod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="settlementtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.tblcontracts" Member="tblcontracts">
    <Type Name="tblcontract">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contractname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="month" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="monthint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.tbldailycontractsettlements" Member="tbldailycontractsettlements">
    <Type Name="tbldailycontractsettlement">
      <Column Name="iddailycontractsettlements" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="settlement" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="openinterest" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.tbloptions" Member="tbloptions">
    <Type Name="tbloption">
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optionname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonth" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonthint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionyear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strikeprice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="callorput" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.tbloptiondata" Member="tbloptiondatas">
    <Type Name="tbloptiondata">
      <Column Name="idoptiondata" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="impliedvol" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="timetoexpinyears" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tblcontracts" Member="test_tblcontracts">
    <Type Name="test_tblcontract">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contractname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="month" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="monthint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tbldailycontractsettlements" Member="test_tbldailycontractsettlements">
    <Type Name="test_tbldailycontractsettlement">
      <Column Name="iddailycontractsettlements" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="settlement" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="openinterest" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tbloptions" Member="test_tbloptions">
    <Type Name="test_tbloption">
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optionname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonth" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonthint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionyear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strikeprice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="callorput" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tbloptiondata" Member="test_tbloptiondatas">
    <Type Name="test_tbloptiondata">
      <Column Name="idoptiondata" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="impliedvol" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="timetoexpinyears" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.tbloptioninputdata" Member="tbloptioninputdatas">
    <Type Name="tbloptioninputdata">
      <Column Name="idoptioninputdata" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idoptioninputsymbol" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="optioninputdatetime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="optioninputopen" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optioninputhigh" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optioninputlow" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="optioninputclose" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.tbloptioninputsymbols" Member="tbloptioninputsymbols">
    <Type Name="tbloptioninputsymbol">
      <Column Name="idoptioninputsymbol" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optioninputcqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="idoptioninputtype" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="multiplier" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="cqgdb.sp_updateContractTblFromSpanUpsert" Method="sp_updateContractTblFromSpanUpsert">
    <Parameter Name="contractname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="month" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="monthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="idinstrument" Type="System.Int32" DbType="Int" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <ElementType Name="sp_updateContractTblFromSpanUpsertResult">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="cqgdb.sp_updateOrInsertContractSettlementsFromSpanUpsert" Method="sp_updateOrInsertContractSettlementsFromSpanUpsert">
    <Parameter Name="futureContractID" Type="System.Int32" DbType="Int" />
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.sp_updateOrInsertTbloptionsInfoAndDataUpsert" Method="sp_updateOrInsertTbloptionsInfoAndDataUpsert">
    <Parameter Name="optionname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="optionmonth" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="optionmonthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="optionyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="strikeprice" Type="System.Double" DbType="Float" />
    <Parameter Name="callorput" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="idinstrument" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idcontract" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="datetime" Type="System.DateTime" DbType="Date" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="impliedvol" Type="System.Double" DbType="Float" />
    <Parameter Name="timetoexpinyears" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_sp_updateContractTblFromSpanUpsert" Method="test_sp_updateContractTblFromSpanUpsert">
    <Parameter Name="contractname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="month" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="monthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="idinstrument" Type="System.Int32" DbType="Int" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <ElementType Name="test_sp_updateContractTblFromSpanUpsertResult">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="cqgdb.test_sp_updateOrInsertContractSettlementsFromSpanUpsert" Method="test_sp_updateOrInsertContractSettlementsFromSpanUpsert">
    <Parameter Name="futureContractID" Type="System.Int32" DbType="Int" />
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_sp_updateOrInsertTbloptionsInfoAndDataUpsert" Method="test_sp_updateOrInsertTbloptionsInfoAndDataUpsert">
    <Parameter Name="optionname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="optionmonth" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="optionmonthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="optionyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="strikeprice" Type="System.Double" DbType="Float" />
    <Parameter Name="callorput" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="idinstrument" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idcontract" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="datetime" Type="System.DateTime" DbType="Date" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="impliedvol" Type="System.Double" DbType="Float" />
    <Parameter Name="timetoexpinyears" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPF" Method="test_SPF">
    <Parameter Name="contractname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="month" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="monthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="idinstrument" Type="System.Int32" DbType="Int" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPDF" Method="test_SPDF">
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Parameter Name="monthChar" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="yearInt" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPO" Method="test_SPO">
    <Parameter Name="optionname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="optionmonth" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="optionmonthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="optionyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="strikeprice" Type="System.Double" DbType="Float" />
    <Parameter Name="callorput" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="idinstrument" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPOD" Method="test_SPOD">
    <Parameter Name="optionmonth" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="optionyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="datetime" Type="System.DateTime" DbType="Date" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="impliedvol" Type="System.Double" DbType="Float" />
    <Parameter Name="timetoexpinyears" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPDF" Method="test_SPDF1">
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Parameter Name="monthChar" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="yearInt" Type="System.Int32" DbType="Int" />
    <Parameter Name="volume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="openinterest" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPDF" Method="test_SPDF2">
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Parameter Name="monthChar" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="yearInt" Type="System.Int32" DbType="Int" />
    <Parameter Name="volume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="openinterest" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_SPDF" Method="test_SPDF3">
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Parameter Name="monthChar" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="yearInt" Type="System.Int32" DbType="Int" />
    <Parameter Name="volume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="openinterest" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
</Database>