<?xml version="1.0" encoding="utf-8"?><Database Name="TestDatabase" Class="LocalEntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TestDatabase.mdf;Integrated Security=True" SettingsObjectName="ICE_Import.Properties.Settings" SettingsPropertyName="TestDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.options" Member="options">
    <Type Name="option">
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="optionname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonth" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonthint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionyear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strikeprice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="callorput" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.contracts" Member="contracts">
    <Type Name="contract">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="contractname" Type="System.String" DbType="VarChar(45) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="month" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="monthint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.dailycontractsettlements" Member="dailycontractsettlements">
    <Type Name="dailycontractsettlement">
      <Column Name="iddailycontractsettlements" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="settlement" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="openinterest" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.optiondata" Member="optiondatas">
    <Type Name="optiondata">
      <Column Name="idoptiondata" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="impliedvol" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="timetoexpinyear" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>