#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICE_Import
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDatabase")]
	public partial class LocalEntitiesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertoption(option instance);
    partial void Updateoption(option instance);
    partial void Deleteoption(option instance);
    partial void Insertcontract(contract instance);
    partial void Updatecontract(contract instance);
    partial void Deletecontract(contract instance);
    partial void Insertdailycontractsettlement(dailycontractsettlement instance);
    partial void Updatedailycontractsettlement(dailycontractsettlement instance);
    partial void Deletedailycontractsettlement(dailycontractsettlement instance);
    partial void Insertoptiondata(optiondata instance);
    partial void Updateoptiondata(optiondata instance);
    partial void Deleteoptiondata(optiondata instance);
    #endregion
		
		public LocalEntitiesDataContext() : 
				base(global::ICE_Import.Properties.Settings.Default.TestDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LocalEntitiesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocalEntitiesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocalEntitiesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocalEntitiesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<option> options
		{
			get
			{
				return this.GetTable<option>();
			}
		}
		
		public System.Data.Linq.Table<contract> contracts
		{
			get
			{
				return this.GetTable<contract>();
			}
		}
		
		public System.Data.Linq.Table<dailycontractsettlement> dailycontractsettlements
		{
			get
			{
				return this.GetTable<dailycontractsettlement>();
			}
		}
		
		public System.Data.Linq.Table<optiondata> optiondatas
		{
			get
			{
				return this.GetTable<optiondata>();
			}
		}
	}
	
	[Table(Name="dbo.options")]
	public partial class option : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idoption;
		
		private string _optionname;
		
		private char _optionmonth;
		
		private int _optionmonthint;
		
		private int _optionyear;
		
		private double _strikeprice;
		
		private char _callorput;
		
		private long _idinstrument;
		
		private System.DateTime _expirationdate;
		
		private long _idcontract;
		
		private string _cqgsymbol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidoptionChanging(long value);
    partial void OnidoptionChanged();
    partial void OnoptionnameChanging(string value);
    partial void OnoptionnameChanged();
    partial void OnoptionmonthChanging(char value);
    partial void OnoptionmonthChanged();
    partial void OnoptionmonthintChanging(int value);
    partial void OnoptionmonthintChanged();
    partial void OnoptionyearChanging(int value);
    partial void OnoptionyearChanged();
    partial void OnstrikepriceChanging(double value);
    partial void OnstrikepriceChanged();
    partial void OncallorputChanging(char value);
    partial void OncallorputChanged();
    partial void OnidinstrumentChanging(long value);
    partial void OnidinstrumentChanged();
    partial void OnexpirationdateChanging(System.DateTime value);
    partial void OnexpirationdateChanged();
    partial void OnidcontractChanging(long value);
    partial void OnidcontractChanged();
    partial void OncqgsymbolChanging(string value);
    partial void OncqgsymbolChanged();
    #endregion
		
		public option()
		{
			OnCreated();
		}
		
		[Column(Storage="_idoption", DbType="BigInt NOT NULL", IsPrimaryKey=true, IsDbGenerated = true)]
		public long idoption
		{
			get
			{
				return this._idoption;
			}
			set
			{
				if ((this._idoption != value))
				{
					this.OnidoptionChanging(value);
					this.SendPropertyChanging();
					this._idoption = value;
					this.SendPropertyChanged("idoption");
					this.OnidoptionChanged();
				}
			}
		}
		
		[Column(Storage="_optionname", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string optionname
		{
			get
			{
				return this._optionname;
			}
			set
			{
				if ((this._optionname != value))
				{
					this.OnoptionnameChanging(value);
					this.SendPropertyChanging();
					this._optionname = value;
					this.SendPropertyChanged("optionname");
					this.OnoptionnameChanged();
				}
			}
		}
		
		[Column(Storage="_optionmonth", DbType="Char(1) NOT NULL")]
		public char optionmonth
		{
			get
			{
				return this._optionmonth;
			}
			set
			{
				if ((this._optionmonth != value))
				{
					this.OnoptionmonthChanging(value);
					this.SendPropertyChanging();
					this._optionmonth = value;
					this.SendPropertyChanged("optionmonth");
					this.OnoptionmonthChanged();
				}
			}
		}
		
		[Column(Storage="_optionmonthint", DbType="Int NOT NULL")]
		public int optionmonthint
		{
			get
			{
				return this._optionmonthint;
			}
			set
			{
				if ((this._optionmonthint != value))
				{
					this.OnoptionmonthintChanging(value);
					this.SendPropertyChanging();
					this._optionmonthint = value;
					this.SendPropertyChanged("optionmonthint");
					this.OnoptionmonthintChanged();
				}
			}
		}
		
		[Column(Storage="_optionyear", DbType="Int NOT NULL")]
		public int optionyear
		{
			get
			{
				return this._optionyear;
			}
			set
			{
				if ((this._optionyear != value))
				{
					this.OnoptionyearChanging(value);
					this.SendPropertyChanging();
					this._optionyear = value;
					this.SendPropertyChanged("optionyear");
					this.OnoptionyearChanged();
				}
			}
		}
		
		[Column(Storage="_strikeprice", DbType="Float NOT NULL")]
		public double strikeprice
		{
			get
			{
				return this._strikeprice;
			}
			set
			{
				if ((this._strikeprice != value))
				{
					this.OnstrikepriceChanging(value);
					this.SendPropertyChanging();
					this._strikeprice = value;
					this.SendPropertyChanged("strikeprice");
					this.OnstrikepriceChanged();
				}
			}
		}
		
		[Column(Storage="_callorput", DbType="Char(1) NOT NULL")]
		public char callorput
		{
			get
			{
				return this._callorput;
			}
			set
			{
				if ((this._callorput != value))
				{
					this.OncallorputChanging(value);
					this.SendPropertyChanging();
					this._callorput = value;
					this.SendPropertyChanged("callorput");
					this.OncallorputChanged();
				}
			}
		}
		
		[Column(Storage="_idinstrument", DbType="BigInt NOT NULL")]
		public long idinstrument
		{
			get
			{
				return this._idinstrument;
			}
			set
			{
				if ((this._idinstrument != value))
				{
					this.OnidinstrumentChanging(value);
					this.SendPropertyChanging();
					this._idinstrument = value;
					this.SendPropertyChanged("idinstrument");
					this.OnidinstrumentChanged();
				}
			}
		}
		
		[Column(Storage="_expirationdate", DbType="Date NOT NULL")]
		public System.DateTime expirationdate
		{
			get
			{
				return this._expirationdate;
			}
			set
			{
				if ((this._expirationdate != value))
				{
					this.OnexpirationdateChanging(value);
					this.SendPropertyChanging();
					this._expirationdate = value;
					this.SendPropertyChanged("expirationdate");
					this.OnexpirationdateChanged();
				}
			}
		}
		
		[Column(Storage="_idcontract", DbType="BigInt NOT NULL")]
		public long idcontract
		{
			get
			{
				return this._idcontract;
			}
			set
			{
				if ((this._idcontract != value))
				{
					this.OnidcontractChanging(value);
					this.SendPropertyChanging();
					this._idcontract = value;
					this.SendPropertyChanged("idcontract");
					this.OnidcontractChanged();
				}
			}
		}
		
		[Column(Storage="_cqgsymbol", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string cqgsymbol
		{
			get
			{
				return this._cqgsymbol;
			}
			set
			{
				if ((this._cqgsymbol != value))
				{
					this.OncqgsymbolChanging(value);
					this.SendPropertyChanging();
					this._cqgsymbol = value;
					this.SendPropertyChanged("cqgsymbol");
					this.OncqgsymbolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.contracts")]
	public partial class contract : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idcontract;
		
		private string _contractname;
		
		private char _month;
		
		private short _monthint;
		
		private long _year;
		
		private long _idinstrument;
		
		private System.DateTime _expirationdate;
		
		private string _cqgsymbol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcontractChanging(long value);
    partial void OnidcontractChanged();
    partial void OncontractnameChanging(string value);
    partial void OncontractnameChanged();
    partial void OnmonthChanging(char value);
    partial void OnmonthChanged();
    partial void OnmonthintChanging(short value);
    partial void OnmonthintChanged();
    partial void OnyearChanging(long value);
    partial void OnyearChanged();
    partial void OnidinstrumentChanging(long value);
    partial void OnidinstrumentChanged();
    partial void OnexpirationdateChanging(System.DateTime value);
    partial void OnexpirationdateChanged();
    partial void OncqgsymbolChanging(string value);
    partial void OncqgsymbolChanged();
    #endregion
		
		public contract()
		{
			OnCreated();
		}
		
		[Column(Storage="_idcontract", DbType="BigInt NOT NULL", IsPrimaryKey = true, IsDbGenerated = true)]
		public long idcontract
		{
			get
			{
				return this._idcontract;
			}
			set
			{
				if ((this._idcontract != value))
				{
					this.OnidcontractChanging(value);
					this.SendPropertyChanging();
					this._idcontract = value;
					this.SendPropertyChanged("idcontract");
					this.OnidcontractChanged();
				}
			}
		}
		
		[Column(Storage="_contractname", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string contractname
		{
			get
			{
				return this._contractname;
			}
			set
			{
				if ((this._contractname != value))
				{
					this.OncontractnameChanging(value);
					this.SendPropertyChanging();
					this._contractname = value;
					this.SendPropertyChanged("contractname");
					this.OncontractnameChanged();
				}
			}
		}
		
		[Column(Storage="_month", DbType="Char(1) NOT NULL")]
		public char month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[Column(Storage="_monthint", DbType="SmallInt NOT NULL")]
		public short monthint
		{
			get
			{
				return this._monthint;
			}
			set
			{
				if ((this._monthint != value))
				{
					this.OnmonthintChanging(value);
					this.SendPropertyChanging();
					this._monthint = value;
					this.SendPropertyChanged("monthint");
					this.OnmonthintChanged();
				}
			}
		}
		
		[Column(Storage="_year", DbType="BigInt NOT NULL")]
		public long year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[Column(Storage="_idinstrument", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long idinstrument
		{
			get
			{
				return this._idinstrument;
			}
			set
			{
				if ((this._idinstrument != value))
				{
					this.OnidinstrumentChanging(value);
					this.SendPropertyChanging();
					this._idinstrument = value;
					this.SendPropertyChanged("idinstrument");
					this.OnidinstrumentChanged();
				}
			}
		}
		
		[Column(Storage="_expirationdate", DbType="Date NOT NULL")]
		public System.DateTime expirationdate
		{
			get
			{
				return this._expirationdate;
			}
			set
			{
				if ((this._expirationdate != value))
				{
					this.OnexpirationdateChanging(value);
					this.SendPropertyChanging();
					this._expirationdate = value;
					this.SendPropertyChanged("expirationdate");
					this.OnexpirationdateChanged();
				}
			}
		}
		
		[Column(Storage="_cqgsymbol", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string cqgsymbol
		{
			get
			{
				return this._cqgsymbol;
			}
			set
			{
				if ((this._cqgsymbol != value))
				{
					this.OncqgsymbolChanging(value);
					this.SendPropertyChanging();
					this._cqgsymbol = value;
					this.SendPropertyChanged("cqgsymbol");
					this.OncqgsymbolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.dailycontractsettlements")]
	public partial class dailycontractsettlement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _iddailycontractsettlements;
		
		private long _idcontract;
		
		private System.DateTime _date;
		
		private double _settlement;
		
		private long _volume;
		
		private long _openinterest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniddailycontractsettlementsChanging(long value);
    partial void OniddailycontractsettlementsChanged();
    partial void OnidcontractChanging(long value);
    partial void OnidcontractChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OnsettlementChanging(double value);
    partial void OnsettlementChanged();
    partial void OnvolumeChanging(long value);
    partial void OnvolumeChanged();
    partial void OnopeninterestChanging(long value);
    partial void OnopeninterestChanged();
    #endregion
		
		public dailycontractsettlement()
		{
			OnCreated();
		}
		
		[Column(Storage="_iddailycontractsettlements", DbType="BigInt NOT NULL", IsPrimaryKey=true, IsDbGenerated = true)]
		public long iddailycontractsettlements
		{
			get
			{
				return this._iddailycontractsettlements;
			}
			set
			{
				if ((this._iddailycontractsettlements != value))
				{
					this.OniddailycontractsettlementsChanging(value);
					this.SendPropertyChanging();
					this._iddailycontractsettlements = value;
					this.SendPropertyChanged("iddailycontractsettlements");
					this.OniddailycontractsettlementsChanged();
				}
			}
		}
		
		[Column(Storage="_idcontract", DbType="BigInt NOT NULL")]
		public long idcontract
		{
			get
			{
				return this._idcontract;
			}
			set
			{
				if ((this._idcontract != value))
				{
					this.OnidcontractChanging(value);
					this.SendPropertyChanging();
					this._idcontract = value;
					this.SendPropertyChanged("idcontract");
					this.OnidcontractChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Column(Storage="_settlement", DbType="Float NOT NULL")]
		public double settlement
		{
			get
			{
				return this._settlement;
			}
			set
			{
				if ((this._settlement != value))
				{
					this.OnsettlementChanging(value);
					this.SendPropertyChanging();
					this._settlement = value;
					this.SendPropertyChanged("settlement");
					this.OnsettlementChanged();
				}
			}
		}
		
		[Column(Storage="_volume", DbType="BigInt NOT NULL")]
		public long volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[Column(Storage="_openinterest", DbType="BigInt NOT NULL")]
		public long openinterest
		{
			get
			{
				return this._openinterest;
			}
			set
			{
				if ((this._openinterest != value))
				{
					this.OnopeninterestChanging(value);
					this.SendPropertyChanging();
					this._openinterest = value;
					this.SendPropertyChanged("openinterest");
					this.OnopeninterestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.optiondata")]
	public partial class optiondata : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idoptiondata;
		
		private long _idoption;
		
		private System.DateTime _datetime;
		
		private double _price;
		
		private double _impliedvol;
		
		private double _timetoexpinyear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidoptiondataChanging(long value);
    partial void OnidoptiondataChanged();
    partial void OnidoptionChanging(long value);
    partial void OnidoptionChanged();
    partial void OndatetimeChanging(System.DateTime value);
    partial void OndatetimeChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void OnimpliedvolChanging(double value);
    partial void OnimpliedvolChanged();
    partial void OntimetoexpinyearChanging(double value);
    partial void OntimetoexpinyearChanged();
    #endregion
		
		public optiondata()
		{
			OnCreated();
		}
		
		[Column(Storage="_idoptiondata", DbType="BigInt NOT NULL", IsPrimaryKey=true, IsDbGenerated = true)]
		public long idoptiondata
		{
			get
			{
				return this._idoptiondata;
			}
			set
			{
				if ((this._idoptiondata != value))
				{
					this.OnidoptiondataChanging(value);
					this.SendPropertyChanging();
					this._idoptiondata = value;
					this.SendPropertyChanged("idoptiondata");
					this.OnidoptiondataChanged();
				}
			}
		}
		
		[Column(Storage="_idoption", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long idoption
		{
			get
			{
				return this._idoption;
			}
			set
			{
				if ((this._idoption != value))
				{
					this.OnidoptionChanging(value);
					this.SendPropertyChanging();
					this._idoption = value;
					this.SendPropertyChanged("idoption");
					this.OnidoptionChanged();
				}
			}
		}
		
		[Column(Storage="_datetime", DbType="DateTime2 NOT NULL", IsPrimaryKey=true)]
		public System.DateTime datetime
		{
			get
			{
				return this._datetime;
			}
			set
			{
				if ((this._datetime != value))
				{
					this.OndatetimeChanging(value);
					this.SendPropertyChanging();
					this._datetime = value;
					this.SendPropertyChanged("datetime");
					this.OndatetimeChanged();
				}
			}
		}
		
		[Column(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[Column(Storage="_impliedvol", DbType="Float NOT NULL")]
		public double impliedvol
		{
			get
			{
				return this._impliedvol;
			}
			set
			{
				if ((this._impliedvol != value))
				{
					this.OnimpliedvolChanging(value);
					this.SendPropertyChanging();
					this._impliedvol = value;
					this.SendPropertyChanged("impliedvol");
					this.OnimpliedvolChanged();
				}
			}
		}
		
		[Column(Storage="_timetoexpinyear", DbType="Float NOT NULL")]
		public double timetoexpinyear
		{
			get
			{
				return this._timetoexpinyear;
			}
			set
			{
				if ((this._timetoexpinyear != value))
				{
					this.OntimetoexpinyearChanging(value);
					this.SendPropertyChanging();
					this._timetoexpinyear = value;
					this.SendPropertyChanged("timetoexpinyear");
					this.OntimetoexpinyearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
