#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICE_Import
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TMLDB")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbloption(tbloption instance);
    partial void Updatetbloption(tbloption instance);
    partial void Deletetbloption(tbloption instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::ICE_Import.Properties.Settings.Default.TMLDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbloption> tbloptions
		{
			get
			{
				return this.GetTable<tbloption>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cqgdb.tbloptions")]
	public partial class tbloption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idoption;
		
		private string _optionname;
		
		private char _optionmonth;
		
		private int _optionmonthint;
		
		private int _optionyear;
		
		private decimal _strikeprice;
		
		private char _callorput;
		
		private long _idinstrument;
		
		private System.DateTime _expirationdate;
		
		private long _idcontract;
		
		private string _cqgsymbol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidoptionChanging(long value);
    partial void OnidoptionChanged();
    partial void OnoptionnameChanging(string value);
    partial void OnoptionnameChanged();
    partial void OnoptionmonthChanging(char value);
    partial void OnoptionmonthChanged();
    partial void OnoptionmonthintChanging(int value);
    partial void OnoptionmonthintChanged();
    partial void OnoptionyearChanging(int value);
    partial void OnoptionyearChanged();
    partial void OnstrikepriceChanging(decimal value);
    partial void OnstrikepriceChanged();
    partial void OncallorputChanging(char value);
    partial void OncallorputChanged();
    partial void OnidinstrumentChanging(long value);
    partial void OnidinstrumentChanged();
    partial void OnexpirationdateChanging(System.DateTime value);
    partial void OnexpirationdateChanged();
    partial void OnidcontractChanging(long value);
    partial void OnidcontractChanged();
    partial void OncqgsymbolChanging(string value);
    partial void OncqgsymbolChanged();
    #endregion
		
		public tbloption()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idoption", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idoption
		{
			get
			{
				return this._idoption;
			}
			set
			{
				if ((this._idoption != value))
				{
					this.OnidoptionChanging(value);
					this.SendPropertyChanging();
					this._idoption = value;
					this.SendPropertyChanged("idoption");
					this.OnidoptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionname", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string optionname
		{
			get
			{
				return this._optionname;
			}
			set
			{
				if ((this._optionname != value))
				{
					this.OnoptionnameChanging(value);
					this.SendPropertyChanging();
					this._optionname = value;
					this.SendPropertyChanged("optionname");
					this.OnoptionnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionmonth", DbType="Char(1) NOT NULL")]
		public char optionmonth
		{
			get
			{
				return this._optionmonth;
			}
			set
			{
				if ((this._optionmonth != value))
				{
					this.OnoptionmonthChanging(value);
					this.SendPropertyChanging();
					this._optionmonth = value;
					this.SendPropertyChanged("optionmonth");
					this.OnoptionmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionmonthint", DbType="Int NOT NULL")]
		public int optionmonthint
		{
			get
			{
				return this._optionmonthint;
			}
			set
			{
				if ((this._optionmonthint != value))
				{
					this.OnoptionmonthintChanging(value);
					this.SendPropertyChanging();
					this._optionmonthint = value;
					this.SendPropertyChanged("optionmonthint");
					this.OnoptionmonthintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionyear", DbType="Int NOT NULL")]
		public int optionyear
		{
			get
			{
				return this._optionyear;
			}
			set
			{
				if ((this._optionyear != value))
				{
					this.OnoptionyearChanging(value);
					this.SendPropertyChanging();
					this._optionyear = value;
					this.SendPropertyChanged("optionyear");
					this.OnoptionyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strikeprice", DbType="Decimal(18,8) NOT NULL")]
		public decimal strikeprice
		{
			get
			{
				return this._strikeprice;
			}
			set
			{
				if ((this._strikeprice != value))
				{
					this.OnstrikepriceChanging(value);
					this.SendPropertyChanging();
					this._strikeprice = value;
					this.SendPropertyChanged("strikeprice");
					this.OnstrikepriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_callorput", DbType="Char(1) NOT NULL")]
		public char callorput
		{
			get
			{
				return this._callorput;
			}
			set
			{
				if ((this._callorput != value))
				{
					this.OncallorputChanging(value);
					this.SendPropertyChanging();
					this._callorput = value;
					this.SendPropertyChanged("callorput");
					this.OncallorputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idinstrument", DbType="BigInt NOT NULL")]
		public long idinstrument
		{
			get
			{
				return this._idinstrument;
			}
			set
			{
				if ((this._idinstrument != value))
				{
					this.OnidinstrumentChanging(value);
					this.SendPropertyChanging();
					this._idinstrument = value;
					this.SendPropertyChanged("idinstrument");
					this.OnidinstrumentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expirationdate", DbType="Date NOT NULL")]
		public System.DateTime expirationdate
		{
			get
			{
				return this._expirationdate;
			}
			set
			{
				if ((this._expirationdate != value))
				{
					this.OnexpirationdateChanging(value);
					this.SendPropertyChanging();
					this._expirationdate = value;
					this.SendPropertyChanged("expirationdate");
					this.OnexpirationdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcontract", DbType="BigInt NOT NULL")]
		public long idcontract
		{
			get
			{
				return this._idcontract;
			}
			set
			{
				if ((this._idcontract != value))
				{
					this.OnidcontractChanging(value);
					this.SendPropertyChanging();
					this._idcontract = value;
					this.SendPropertyChanged("idcontract");
					this.OnidcontractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cqgsymbol", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string cqgsymbol
		{
			get
			{
				return this._cqgsymbol;
			}
			set
			{
				if ((this._cqgsymbol != value))
				{
					this.OncqgsymbolChanging(value);
					this.SendPropertyChanging();
					this._cqgsymbol = value;
					this.SendPropertyChanged("cqgsymbol");
					this.OncqgsymbolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
