<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="TestOFDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="ICE_Import.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="cqgdb.test_tblcontracts" Member="test_tblcontracts">
    <Type Name="test_tblcontract">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contractname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="month" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="monthint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tbldailycontractsettlements" Member="test_tbldailycontractsettlements">
    <Type Name="test_tbldailycontractsettlement">
      <Column Name="iddailycontractsettlements" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="settlement" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="openinterest" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tbloptiondata" Member="test_tbloptiondatas">
    <Type Name="test_tbloptiondata">
      <Column Name="idoptiondata" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="impliedvol" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="timetoexpinyears" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="cqgdb.test_tbloptions" Member="test_tbloptions">
    <Type Name="test_tbloption">
      <Column Name="idoption" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optionname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonth" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="optionmonthint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="optionyear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strikeprice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="callorput" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="idinstrument" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="expirationdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cqgsymbol" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="cqgdb.test_sp_updateContractTblFromSpanUpsert" Method="test_sp_updateContractTblFromSpanUpsert">
    <Parameter Name="contractname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="month" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="monthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="idinstrument" Type="System.Int32" DbType="Int" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <ElementType Name="test_sp_updateContractTblFromSpanUpsertResult">
      <Column Name="idcontract" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="cqgdb.test_sp_updateOrInsertContractSettlementsFromSpanUpsert" Method="test_sp_updateOrInsertContractSettlementsFromSpanUpsert">
    <Parameter Name="futureContractID" Type="System.Int32" DbType="Int" />
    <Parameter Name="spanDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="settlementPrice" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="cqgdb.test_sp_updateOrInsertTbloptionsInfoAndDataUpsert" Method="test_sp_updateOrInsertTbloptionsInfoAndDataUpsert">
    <Parameter Name="optionname" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="optionmonth" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="optionmonthint" Type="System.Int32" DbType="Int" />
    <Parameter Name="optionyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="strikeprice" Type="System.Double" DbType="Float" />
    <Parameter Name="callorput" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="idinstrument" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="expirationdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idcontract" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="cqgsymbol" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="datetime" Type="System.DateTime" DbType="Date" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="impliedvol" Type="System.Double" DbType="Float" />
    <Parameter Name="timetoexpinyears" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
</Database>